### ISSUE TITLE
Señales salientes de la ALU

### ISSUE THREAD

**Issue by Mdelaf** [IIC2343-2016-1/syllabus#2]
En el enunciado se dice que debemos mostrar 4 señales salientes de la ALU, sin embargo se refieren sólo a dos de ellas (Z y N). ¿Cuáles son las otras dos señales que tenemos que mostrar?

**Comment by FranLucchini** [comment]
Para esta entrega deben usar solo dos señales, es un error en el enunciado. Mientras sepan cual muestra Z y cuál muestra N, está todo bien. Los leds que les sobran los pueden usar para lo que quieran.
