### ISSUE TITLE
Informe entrega 1

### ISSUE THREAD

**Issue by FranciscoRencoret1** [IIC2343-2016-1/syllabus#3]
Hola, una pregunta, el informe donde hay que explicar que hizo cada uno y la nota individual que le ponemos al resto del equipo tenemos que hacerlo en un word ? Como se entrega eso? Se entrega junto o separado?

**Comment by FranLucchini** [comment]
Saludos,

En el informe deben describir de forma resumida qué hizo cada integrante. Las notas de la co-evaluación la respoderán en un Google Form que todavía no está disponible. El link será enviado por el Siding.

El informe pueden hacerlo en word, latex o editor de texto preferido. Mientras esté ordenado y contenga lo que se pide, está bien. Por último, el informe deben entregarlo junto al proyecto base en su repositorio.
